---

- hosts: webservers
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Deleting older version
      command: rm -rf /home/ubuntu/inlinescriptchatapp

    - name: update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes    

    - name: Install required base packages
      apt: pkg={{ item }} state=present
      with_items:
        - python3
        - python3-dev
        - git
        - nginx
        - gunicorn
        - postgresql-common
      tags:
        - [packages]

    - name: Clone ChatApplication from Github
      git:
        repo: https://github.com/parepallirevanth/DevopsWebApp.git
        dest: /home/chatuser/AnsibleTestApp
        version: master
        force: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install virtualenv
      command: pip3 install virtualenv

    - name: creating virtualenv
      command: virtualenv -p /usr/bin/python3 /home/chatuser/AnsibleTestApp/venv


    - name: Activate env
      command: cd /home/chatuser/AnsibleTestApp/venv ; source bin/activate
      command: /home/chatuser/AnsibleTestApp/venv/bin/pip3 install -r /home/chatuser/AnsibleTestApp/chatapplication/requirements.txt

    - name: django extensions
      command: pip3 install django bcrypt django-extensions
      
    - name: Execute
      file:
        path: /home/chatuser/AnsibleTestApp/chatapplication/manage.py
        mode: '0777'

    - name: collect static files
      django_manage:
        command: collectstatic
        virtualenv: /home/chatuser/AnsibleTestApp/venv
        app_path: /home/chatuser/AnsibleTestApp/chatapplication

    - name: Change file ownership and permissions
      file:
         path: /home/chatuser/AnsibleTestApp
         owner: chatuser
         group: www-data
         mode: '0755'
         state: directory
         recurse: yes

    - name: gunicorn service to remote host
      copy:
        src: /home/revanth/Ansible/gunicorn.service
        dest: /etc/systemd/system/
 
    - name: restart service gunicorn
      systemd:
        name: gunicorn
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: execute
      file:
        path: /etc/systemd/system/gunicorn.service
        mode: '0644'
    
    - name: Ansible copy file force
      copy:
        src: /home/revanth/Ansible/nginx
        dest: /etc/nginx/sites-available/chat1

    - name: configuraging nginx
      command:  nginx -t

    - name: configuration nginx
      command: ln -s /etc/nginx/sites-available/chat1 /etc/nginx/sites-enabled

    - name: restart service nginx
      systemd:
        state: restarted
        name: nginx

    - name: restart service gunicorn again
      systemd:
        state: restarted
        name: gunicorn 

